### ISSUE TITLE
Regression from v`1.0.0`

### ISSUE THREAD

**Issue by Rudxain** [frewsxcv/rust-dark-light#39]
Universal-Debloater-Alliance/universal-android-debloater-next-generation#627

`src/main.rs`:
```rust
fn main() {
    println!("{:?}", dark_light::detect());
}
```

`Cargo.toml`:
```toml
[package]
name = "tmp"
version = "0.1.0"
edition = "2021"
```
```toml
[dependencies]
dark-light = "=1.1.1"
# `cargo run`: "Light"
```
```toml
[dependencies]
dark-light = "=1.0.0"
# `cargo run`: "Dark" (correct)
```

The 2 variations of `dependencies` from `Cargo.toml` where tested on **separate directories**, for better isolation (no need for `cargo update`) and to avoid recompilation of recursive deps (although I tried to recycle `target/`)
